### ISSUE TITLE
Huffman coding

### ISSUE THREAD

**Issue by epsitec** [bigmachine-io/imposter-v2#1]
Hi Rob and Scott, I am glad to see your work on the *imposter's handbook* continue with this 2nd edition.

If you are going to explain compression, I kindly suggest that you also include a chapter on [Huffman coding](https://en.wikipedia.org/wiki/Huffman_coding) which is essential to understand how adaptive compressions like LZW work. And maybe you should start with [Morse code](https://en.wikipedia.org/wiki/Morse_code) which also attempts to reduce the amount of information when _encoding_ text. And an excursion in the territory of [entropy](https://math.stackexchange.com/questions/181443/how-are-huffman-encoding-and-entropy-related) should probably be included too...

**Comment by robconery** [comment]
All of these topics are in the book - in fact we do Huffman's algorithm to derive a prefix free code. I also go into Hartley and Shannon entropy in detail and yes, discuss Morse code. Have you read the book yet?

**Comment by epsitec** [comment]
Oh - sorry for the noise. No, I did not yet browse through the book. However, I had read one of your posts where you gave an outline of the table of contents, which obviously was not detailed enough to reveal the presence of Huffman, Morse and co.
