### ISSUE TITLE
Error with Martin Hellman’s Breakthrough chapter?

### ISSUE THREAD

**Issue by elcortez** [bigmachine-io/imposter-v2#11]
Page 234 of the pdf
"For her secret key, a, Alice picks a 2. She plugs this value into Hellman’s equation along with the algorithm parameters, raising g (5) to the power of her secret key (2) and taking the modulus of n (9) to generate her public key, A"

Therefore, Alice's SECRET KEY is 2, and her PUBLIC KEY is 7.

Also, Bob's SECRET KEY is 4 and his PUBLIC KEY is also 4.

(...)

Page 235
"Alice sends Bob her 7 for her part of the key exchange, and Bob sends Alice his 4"
(...)
"Bob does the same with Alice’s number:"

On the equation that immediatly follows this sentence, Bob uses the number 2, which is Alice's SECRET KEY?! 

How is it possible that Bob has Alice's secret key?

**Comment by robconery** [comment]
LOL yeah - I goofed that up. I'm about to drop an update (probably in the next 5 days) that will address this. Cheers!

**Comment by robconery** [comment]
Sorry - I should be more clear... this is fixed :).

**Comment by elcortez** [comment]
Thanks for your answer !
