### ISSUE TITLE
Season 2 (Publisher’s version: 0.0.3 ) - PDF Page 18 .....rules by which God.  Incomplete?

### ISSUE THREAD

**Issue by Number5isAlive** [bigmachine-io/imposter-v2#6]
PDF Page 18  -- Second Sentence under figure2 George Boole -- Not Grammar, not spelling,  incomplete thought?

He was (as you might suspect) an extremely religious man but was having trouble understanding the rules by which God. 

….. by which God?   did what?  ...looks incomplete.

**Comment by robconery** [comment]
Doh! Thanks! I'll have it in 0.0.5

**Comment by robconery** [comment]
Closing as this was fixed.
