### ISSUE TITLE
Season 2 epub import in kindle, Font selector issue

### ISSUE THREAD

**Issue by mohitt** [bigmachine-io/imposter-v2#8]
I am trying to read the season 2 on an iPad and seems like font selector has some issue. I can only see urdu/arabic option in fonts

![unnamed](https://user-images.githubusercontent.com/919686/69899505-027d4e80-131c-11ea-919a-ea8966c61b7d.png)

**Comment by robconery** [comment]
Hmm - not sure how I can troubleshoot that one. I've tested it out on 3 different generations of iPad and it renders OK. It's epub 3, which is an open standard, and the fonting is handled completely by the reader so there's not much I can do.
